version: '3.1'
services:
  odoo:
    image: odoo:17.0
    ports:
      - '808:8069'
    volumes:
      - 'odoo_data:/bitnami/odoo'
      - ./addons:/mnt/extra-addons
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      #- ODOO_DATABASE_HOST=34.95.178.203
      - ODOO_DATABASE_HOST=10.68.48.9
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=odoo
      - ODOO_DATABASE_NAME=odoo
      - ODOO_DATABASE_PASSWORD=Naipa1Xo
volumes:
  odoo_data:
    driver: local